### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by syryl** [dweinstein/node-google-play-cli#3]
`gp-bulk-details air.WatchESPN com.viber.voip | jq '.'
LoginError: Error=NeedsBrowser
Url=https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/auth?hl%3Dus_us%26xoauth_display_name%3DAndroid%2BLogin%2BService%26source%3DAndroid%2BLogin&plt=AKgnsbs40oYwAw1NKE0nNrslGrO4JScovtb_omZ8JaD9xn_O7Hxj31xuqTLTZwcCy7eNlNyaAy-Fx6WLGXs6-iwSt_tkLPp6XERsjr2y6d9n-cSlwMeyDRJ6mXy6hqa1KLPAo5ddQQ9HB83VSRu971COQ8ZHH5ZIjyDxHFzK0USrorP4nRGg6-glAs_McFyIptrJyOdZmS07JyKivH1rLikSZC81UL9nYJxwc6uR2N32kw0jMc2VtEI
ErrorDetail=To access your account, you must sign in on the web. Touch Next to start browser sign-in.
`
I'm noob on using node.

**Comment by dweinstein** [comment]
sounds like you might first need to login to your account from a device or gmail to unlock your account.
