### ISSUE TITLE
LoginError: Error=BadAuthentication

### ISSUE THREAD

**Issue by jr3074** [dweinstein/node-google-play-cli#5]
Like another google play api, i also get this issue on this app, BadAuthentication

**Comment by dweinstein** [comment]
yeah it seems to happen randomly. Google may be planning to deprecate the auth mechanism being used, so one thing you can do is preserve the authToken and then pass it in via options...

`gpcli_authToken=...token` instead of setting the login/password env vars ought to be enough for now.

**Comment by jr3074** [comment]
how to get the token?

**Comment by dweinstein** [comment]
For now you have two options until I have time to look into the new auth devices may be using:

- mitm a real device with your login and pull it out of the network trace. The token will be in the headers and can be used with this library
- keep trying to auth with this library a few times - it eventually works, then save the token.

**Comment by dweinstein** [comment]
by the way you can use `gp-get-token` binary installed for this w/ `GOOGLE_LOGIN`, `GOOGLE_PASSWORD`, and `ANDROID_ID` set in your environment. if you retry a few times you should eventually get an auth token and then you can use it as I described using the `gpcli_authToken` env variable going forward. That token should remain valid for a while, but I don't know exactly how long.
